export const sortBy = (sortBy: 'priceUp' | 'priceDown' | 'timeInFlight') => ({type: 'sortBy', sortBy: sortBy})
export const filter = (filter: '00' | '01' | '10' | '11') => ({type: 'filter', filter: filter})
export const priceFrom = (price: number) => ({type: 'priceFrom', priceFrom: price})
export const priceTo = (price: number) => ({type: 'priceTo', priceTo: price})
export const addCompanyName = (name: string) => ({type: 'addCompanyName', addCompanyName: name})
export const removeCompanyName = (name: string) => ({type: 'removeCompanyName', removeCompanyName: name})
export const addSelectedCompanyName = (name: string) => ({type: 'addSelectedCompanyName', addSelectedCompanyName: name})
export const removeSelectedCompanyName = (name: string) => ({type: 'removeSelectedCompanyName', removeSelectedCompanyName: name})
export const clearCompanyName = () => ({type: 'clearCompanyNames'})
